language: perl
perl:
- "5.26"
install:
- cpanm --quiet --notest Text::Autoformat
- sudo  apt-get install curl
- export HUGO_VERSION="0.51"
- echo $HUGO_VERSION
- curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" -o "hugo_${HUGO_VERSION}.tar.gz"
- mkdir /tmp/hugo_${HUGO_VERSION}
- tar xf hugo_${HUGO_VERSION}.tar.gz -C /tmp/hugo_${HUGO_VERSION}
- rm hugo_${HUGO_VERSION}.tar.gz
- sudo mv /tmp/hugo_${HUGO_VERSION}/hugo /usr/bin/
- hugo version

script:
- perl ./wild-posts
- bash ./publish-travis.sh

# https://gist.github.com/willprice/e07efd73fb7f13f917ea
env:
  global:
    secure: vYZN2sHkYowlHJueqoteOmusAbp5smODa6CJtEiTBANrMs5/NHhWov7VXS6iMtZASD1kR0Kzo9XBDayO4XhohumGZQXM1Wja6BzNqjZ4W15VMI+kN5gpgEbPvaso5DqY18gmRnkJUZDWrAeSVqRB6AfWuAvpa5NIksm4kXF7wMgcNgReOX4W0NC0GLcy/sqpQsKj45o8vg+tu6ARSIVGASB4uiGIrRBeTxzrFJYatDdEp6h6KlhIDuUfpF8IiC4Lwwe0R1LdR9rFd9A6dutsziwF2SqbBBCpHKYoBpr/oJ4ClIMBepJS9rrVgLdAsgdoxvporCvUev4GwwOULt6YnN0/n/tqGPU2eHdOFkGmLUjbYM7JH1uZr/NWfvi6ETPs1ivz8TG4vJc0TPhRuoDerkeqThtqIA2uaidGLwFZEH1TK5jHPIqwVYRYVQDO3MvWRZ5KX3SVujwXX6KyAboaF/G9hFBiLRjOw4VbhSqj1ZMNXPGeLnWyJlW2sPyHKyZ8xuwDaau2+M/iHdMfCQV85IVlFM1/Tjbkg7cVzjt4EwbYmVsEDBobXfjS+s8iZiQNefiqoJiBiv1W18K+JhH2R3PrOtb8/O3SOPTpoh9n+5XKGU59DrcphMrgTZLWnw/dQUi8ZGOtW6PTUJ9503igHwdrqRlv/bVaK63GpwB9UhA=
