#!/usr/bin/perl
use strict;
use warnings;
use 5.010;
use autodie;
use Getopt::Long;
use Pod::Usage;

# Command line options
GetOptions(
    "h|?|help"   => \my $help,
    "p|post=s"   => \my $post,
    "i|inpost=s" => \my $inpost,
) or pod2usage(1);

# Help
pod2usage( -exitval => 0, -verbose => 2, -noperldoc => 1 ) if $help;

my $POSTSDIR = 'content/posts';

if ($inpost) {
    my @posts = `grep --color=never -l -R -i -E '$inpost' $POSTSDIR | sort | uniq`;
    print for @posts;
} elsif ($post) {
    print sort `find $POSTSDIR -type f -iname "*$post*"`;
} else {
    print sort `find $POSTSDIR -type f`;
}

__END__

=head1 NAME

findp - search through my posts

=head1 SYNOPSIS

findp [options]

  List all posts if no option is used. Searches are case insensitive.

  options:
    -h, -?, --help      brief help message
    -p, --post STRING   find posts with titles containing STRING
    -i, --inpost REGEX  find posts matching egrep REGEX
